// Amaravati Names data set
registerTileNames(7,9,6,"Crystal Fields");
registerTileNames(9,3,6,"Refiners Flame");
registerTileNames(5,3,6,"Arc of the Aether");
registerTileNames(6,7,6,"Monoculture");
registerTileNames(2,4,6,"Constructor Primus");
registerTileNames(8,4,6,"Refiners Flame");
registerTileNames(12,8,6,"Twisted Space");
registerTileNames(-1,9,6,"Twisted Space");
registerTileNames(10,12,6,"Twisted Space");
registerTileNames(7,11,6,"Monoculture");
registerTileNames(3,0,6,"Twisted Void");
registerTileNames(6,8,6,"Monoculture");
registerTileNames(8,7,6,"Manufactury");
registerTileNames(9,12,6,"Twisted Space");
registerTileNames(8,8,6,"Manufactury");
registerTileNames(12,6,6,"Twisted Space");
registerTileNames(10,4,6,"Triad");
registerTileNames(13,5,6,"Twisted Space");
registerTileNames(5,10,6,"Monoculture");
registerTileNames(11,11,6,"Twisted Space");
registerTileNames(4,11,6,"Radiant Armory");
registerTileNames(0,8,6,"Twisted Space");
registerTileNames(12,11,6,"Twisted Space");
registerTileNames(2,6,6,"Monoculture");
registerTileNames(5,5,6,"Monoculture");
registerTileNames(0,1,6,"Twisted Space");
registerTileNames(11,5,6,"Bulwark of the Formal Cause");
registerTileNames(2,7,6,"Monoculture");
registerTileNames(7,7,6,"Crystal Fields");
registerTileNames(-1,8,6,"Twisted Space");
registerTileNames(8,2,6,"Monoculture");
registerTileNames(0,6,6,"Twisted Space");
registerTileNames(7,2,6,"Monoculture");
registerTileNames(8,10,6,"Crystal Fields");
registerTileNames(7,0,6,"Twisted Void");
registerTileNames(11,6,6,"Bulwark of the Formal Cause");
registerTileNames(9,4,6,"Refiners Flame");
registerTileNames(4,2,6,"Monoculture");
registerTileNames(10,6,6,"Monoculture");
registerTileNames(6,2,6,"Monoculture");
registerTileNames(1,11,6,"Twisted Space");
registerTileNames(9,10,6,"Gate of Potentiality");
registerTileNames(13,4,6,"Twisted Space");
registerTileNames(0,12,6,"Twisted Space");
registerTileNames(6,0,6,"Twisted Void");
registerTileNames(-1,10,6,"Twisted Space");
registerTileNames(-1,6,6,"Twisted Space");
registerTileNames(11,4,6,"Triad");
registerTileNames(3,6,6,"Crystal Fields");
registerTileNames(11,12,6,"Twisted Space");
registerTileNames(3,2,6,"Monoculture");
registerTileNames(10,7,6,"Habitation");
registerTileNames(1,4,6,"Twisted Space");
registerTileNames(0,2,6,"Twisted Space");
registerTileNames(8,5,6,"Crystal Fields");
registerTileNames(6,4,6,"Monoculture");
registerTileNames(4,3,6,"Monad");
registerTileNames(4,8,6,"Quenching Waters");
registerTileNames(12,5,6,"Twisted Space");
registerTileNames(0,9,6,"Twisted Space");
registerTileNames(6,12,6,"Twisted Space");
registerTileNames(1,7,6,"Bulwark of the Final Cause");
registerTileNames(2,5,6,"Monoculture");
registerTileNames(2,8,6,"Monoculture");
registerTileNames(2,3,6,"Crystal Fields");
registerTileNames(7,8,6,"Manufactury");
registerTileNames(4,7,6,"Quenching Waters");
registerTileNames(11,10,6,"Twisted Space");
registerTileNames(10,11,6,"Twisted Space");
registerTileNames(2,10,6,"Monoculture");
registerTileNames(0,7,6,"Twisted Space");
registerTileNames(3,3,6,"Gate of Actuality");
registerTileNames(0,5,6,"Twisted Space");
registerTileNames(7,5,6,"Constructor Tertius");
registerTileNames(6,5,6,"Monoculture");
registerTileNames(6,9,6,"Monoculture");
registerTileNames(10,1,6,"Twisted Space");
registerTileNames(5,6,6,"Crystal Fields");
registerTileNames(6,1,6,"Bulwark of the Material Cause");
registerTileNames(11,7,6,"Bulwark of the Formal Cause");
registerTileNames(1,6,6,"Bulwark of the Final Cause");
registerTileNames(10,8,6,"Constructor Quartus");
registerTileNames(12,4,6,"Twisted Space");
registerTileNames(11,2,6,"Twisted Space");
registerTileNames(5,12,6,"Bulwark of the Efficient Cause");
registerTileNames(12,12,6,"Twisted Space");
registerTileNames(9,9,6,"Animalia");
registerTileNames(7,10,6,"Habitation");
registerTileNames(5,9,6,"Dyad");
registerTileNames(10,9,6,"Distillation");
registerTileNames(13,3,6,"Twisted Space");
registerTileNames(5,11,6,"Habitation");
registerTileNames(8,3,6,"Refiners Flame");
registerTileNames(1,10,6,"Twisted Space");
registerTileNames(2,9,6,"Monoculture");
registerTileNames(11,9,6,"Habitation");
registerTileNames(12,2,6,"Twisted Space");
registerTileNames(5,4,6,"Crystal Fields");
registerTileNames(1,9,6,"Habitation");
registerTileNames(9,1,6,"Habitation");
registerTileNames(0,3,6,"Twisted Space");
registerTileNames(10,5,6,"Habitation");
registerTileNames(8,6,6,"Monoculture");
registerTileNames(13,8,6,"Twisted Space");
registerTileNames(-1,7,6,"Twisted Space");
registerTileNames(13,10,6,"Twisted Space");
registerTileNames(1,8,6,"Bulwark of the Final Cause");
registerTileNames(4,10,6,"Monoculture");
registerTileNames(7,3,6,"Habitation");
registerTileNames(10,3,6,"Triad");
registerTileNames(2,1,6,"Twisted Space");
registerTileNames(7,12,6,"Twisted Space");
registerTileNames(4,1,6,"Fermentation");
registerTileNames(8,1,6,"Constructor Secundus");
registerTileNames(11,8,6,"Radiant Armory");
registerTileNames(8,12,6,"Twisted Space");
registerTileNames(5,0,6,"Twisted Void");
registerTileNames(1,12,6,"Twisted Space");
registerTileNames(1,2,6,"Twisted Space");
registerTileNames(12,7,6,"Twisted Space");
registerTileNames(5,1,6,"Bulwark of the Material Cause");
registerTileNames(6,11,6,"Monoculture");
registerTileNames(0,4,6,"Twisted Space");
registerTileNames(9,5,6,"Tower of Purity");
registerTileNames(8,11,6,"Monoculture");
registerTileNames(7,6,6,"Monoculture");
registerTileNames(3,10,6,"Monoculture");
registerTileNames(9,8,6,"Manufactury");
registerTileNames(3,4,6,"Habitation");
registerTileNames(1,3,6,"Twisted Space");
registerTileNames(3,5,6,"Monoculture");
registerTileNames(7,1,6,"Bulwark of the Material Cause");
registerTileNames(5,2,6,"Monoculture");
registerTileNames(13,1,6,"Twisted Space");
registerTileNames(0,11,6,"Twisted Space");
registerTileNames(11,1,6,"Twisted Space");
registerTileNames(11,3,6,"Protozoa");
registerTileNames(10,2,6,"Monoculture");
registerTileNames(12,10,6,"Twisted Space");
registerTileNames(3,12,6,"Bulwark of the Efficient Cause");
registerTileNames(9,2,6,"Monoculture");
registerTileNames(4,0,6,"Twisted Void");
registerTileNames(5,7,6,"Quenching Waters");
registerTileNames(3,11,6,"Constructor Quintus");
registerTileNames(4,5,6,"Monoculture");
registerTileNames(2,2,6,"Monoculture");
registerTileNames(3,1,6,"Crystal Fields");
registerTileNames(1,1,6,"Twisted Space");
registerTileNames(0,10,6,"Twisted Space");
registerTileNames(2,11,6,"Crystal Fields");
registerTileNames(13,7,6,"Twisted Space");
registerTileNames(-1,11,6,"Twisted Space");
registerTileNames(7,4,6,"Radiant Armory");
registerTileNames(6,3,6,"Monoculture");
registerTileNames(10,10,6,"Crystal Fields");
registerTileNames(4,4,6,"Plantae");
registerTileNames(6,6,6,"Monoculture");
registerTileNames(3,8,6,"Gate of the Locomotive");
registerTileNames(2,12,6,"Twisted Space");
registerTileNames(6,10,6,"Monoculture");
registerTileNames(12,9,6,"Twisted Space");
registerTileNames(9,7,6,"Arc of the Primum Mobile");
registerTileNames(13,2,6,"Twisted Space");
registerTileNames(4,9,6,"Dyad");
registerTileNames(4,6,6,"Tower of Law");
registerTileNames(9,6,6,"Monoculture");
registerTileNames(1,5,6,"Monoculture");
registerTileNames(3,9,6,"Arc of the Earth-Moving Fulcrum");
registerTileNames(13,6,6,"Twisted Space");
registerTileNames(3,7,6,"Crystal Fields");
registerTileNames(12,3,6,"Twisted Space");
registerTileNames(4,12,6,"Bulwark of the Efficient Cause");
registerTileNames(8,9,6,"Manufactury");
registerTileNames(9,11,6,"Monoculture");
registerTileNames(13,9,6,"Twisted Space");
registerTileNames(5,8,6,"Quenching Waters");
registerTileNames(12,1,6,"Twisted Space");

// Amaravati Types data set
registerTileTypes(8,6,6,"an Ordered Forest");
registerTileTypes(13,7,6,"a Twisted Space");
registerTileTypes(4,5,6,"an Ordered Forest");
registerTileTypes(7,1,6,"an Empyrean Gate");
registerTileTypes(13,6,6,"a Twisted Space");
registerTileTypes(11,10,6,"a Twisted Space");
registerTileTypes(1,11,6,"a Twisted Space");
registerTileTypes(1,1,6,"a Twisted Space");
registerTileTypes(-1,8,6,"a Twisted Space");
registerTileTypes(2,6,6,"an Ordered Forest");
registerTileTypes(10,1,6,"a Twisted Space");
registerTileTypes(7,0,6,"a Twisted Void");
registerTileTypes(12,3,6,"a Twisted Space");
registerTileTypes(4,10,6,"an Ordered Forest");
registerTileTypes(12,10,6,"a Twisted Space");
registerTileTypes(-1,11,6,"a Twisted Space");
registerTileTypes(0,11,6,"a Twisted Space");
registerTileTypes(4,6,6,"an Ivory Tower");
registerTileTypes(12,2,6,"a Twisted Space");
registerTileTypes(10,2,6,"an Ordered Forest");
registerTileTypes(7,9,6,"an Argentium Remnants");
registerTileTypes(3,9,6,"a Crystal Spire");
registerTileTypes(2,12,6,"a Twisted Space");
registerTileTypes(3,11,6,"an Argent Hatchery");
registerTileTypes(2,9,6,"an Ordered Forest");
registerTileTypes(5,11,6,"an Inn");
registerTileTypes(0,9,6,"a Twisted Space");
registerTileTypes(6,7,6,"an Ordered Forest");
registerTileTypes(7,2,6,"an Ordered Forest");
registerTileTypes(3,1,6,"an Argentium Remnants");
registerTileTypes(3,10,6,"an Ordered Forest");
registerTileTypes(1,8,6,"an Empyrean Gate");
registerTileTypes(0,7,6,"a Twisted Space");
registerTileTypes(11,5,6,"an Empyrean Gate");
registerTileTypes(7,4,6,"a Radiant Armory");
registerTileTypes(2,4,6,"an Argent Hatchery");
registerTileTypes(4,11,6,"a Radiant Armory");
registerTileTypes(4,4,6,"a Vivarium");
registerTileTypes(11,2,6,"a Twisted Space");
registerTileTypes(11,12,6,"a Twisted Space");
registerTileTypes(2,7,6,"an Ordered Forest");
registerTileTypes(7,3,6,"an Inn");
registerTileTypes(10,10,6,"an Argentium Remnants");
registerTileTypes(1,10,6,"a Twisted Space");
registerTileTypes(10,3,6,"a Crystal Castle");
registerTileTypes(3,12,6,"an Empyrean Gate");
registerTileTypes(3,2,6,"an Ordered Forest");
registerTileTypes(3,0,6,"a Twisted Void");
registerTileTypes(9,11,6,"an Ordered Forest");
registerTileTypes(5,10,6,"an Ordered Forest");
registerTileTypes(9,3,6,"a Lake of Fire");
registerTileTypes(10,5,6,"an Inn");
registerTileTypes(6,4,6,"an Ordered Forest");
registerTileTypes(11,4,6,"a Crystal Castle");
registerTileTypes(5,5,6,"an Ordered Forest");
registerTileTypes(2,2,6,"an Ordered Forest");
registerTileTypes(12,11,6,"a Twisted Space");
registerTileTypes(8,8,6,"a Manufactury");
registerTileTypes(6,1,6,"an Empyrean Gate");
registerTileTypes(12,5,6,"a Twisted Space");
registerTileTypes(8,5,6,"an Argentium Remnants");
registerTileTypes(6,3,6,"an Ordered Forest");
registerTileTypes(5,6,6,"an Argentium Remnants");
registerTileTypes(3,5,6,"an Ordered Forest");
registerTileTypes(2,10,6,"an Ordered Forest");
registerTileTypes(4,7,6,"a Cold Sea");
registerTileTypes(4,2,6,"an Ordered Forest");
registerTileTypes(13,10,6,"a Twisted Space");
registerTileTypes(9,4,6,"a Lake of Fire");
registerTileTypes(13,3,6,"a Twisted Space");
registerTileTypes(6,9,6,"an Ordered Forest");
registerTileTypes(9,2,6,"an Ordered Forest");
registerTileTypes(7,11,6,"an Ordered Forest");
registerTileTypes(3,6,6,"an Argentium Remnants");
registerTileTypes(11,7,6,"an Empyrean Gate");
registerTileTypes(0,12,6,"a Twisted Space");
registerTileTypes(5,4,6,"an Argentium Remnants");
registerTileTypes(5,9,6,"a Crystal Castle");
registerTileTypes(11,3,6,"a Vivarium");
registerTileTypes(13,1,6,"a Twisted Space");
registerTileTypes(11,1,6,"a Twisted Space");
registerTileTypes(5,3,6,"a Greater Spire");
registerTileTypes(5,0,6,"a Twisted Void");
registerTileTypes(8,1,6,"an Argent Hatchery");
registerTileTypes(8,2,6,"an Ordered Forest");
registerTileTypes(-1,6,6,"a Twisted Space");
registerTileTypes(2,11,6,"an Argentium Remnants");
registerTileTypes(11,6,6,"an Empyrean Gate");
registerTileTypes(6,5,6,"an Ordered Forest");
registerTileTypes(8,9,6,"a Manufactury");
registerTileTypes(4,3,6,"a Crystal Castle");
registerTileTypes(10,6,6,"an Ordered Forest");
registerTileTypes(12,4,6,"a Twisted Space");
registerTileTypes(0,1,6,"a Twisted Space");
registerTileTypes(7,6,6,"an Ordered Forest");
registerTileTypes(9,1,6,"an Inn");
registerTileTypes(2,3,6,"an Argentium Remnants");
registerTileTypes(13,8,6,"a Twisted Space");
registerTileTypes(0,8,6,"a Twisted Space");
registerTileTypes(13,5,6,"a Twisted Space");
registerTileTypes(10,12,6,"a Twisted Space");
registerTileTypes(5,12,6,"an Empyrean Gate");
registerTileTypes(11,9,6,"an Inn");
registerTileTypes(5,7,6,"a Cold Sea");
registerTileTypes(8,12,6,"a Twisted Space");
registerTileTypes(12,8,6,"a Twisted Space");
registerTileTypes(2,5,6,"an Ordered Forest");
registerTileTypes(3,8,6,"a Clockwork Tower");
registerTileTypes(11,8,6,"a Radiant Armory");
registerTileTypes(1,7,6,"an Empyrean Gate");
registerTileTypes(7,12,6,"a Twisted Space");
registerTileTypes(4,12,6,"an Empyrean Gate");
registerTileTypes(6,6,6,"an Ordered Forest");
registerTileTypes(4,9,6,"a Crystal Castle");
registerTileTypes(12,1,6,"a Twisted Space");
registerTileTypes(8,10,6,"an Argentium Remnants");
registerTileTypes(1,5,6,"an Ordered Forest");
registerTileTypes(0,2,6,"a Twisted Space");
registerTileTypes(0,3,6,"a Twisted Space");
registerTileTypes(6,11,6,"an Ordered Forest");
registerTileTypes(13,4,6,"a Twisted Space");
registerTileTypes(7,5,6,"an Argent Hatchery");
registerTileTypes(10,9,6,"a Tavern");
registerTileTypes(7,8,6,"a Manufactury");
registerTileTypes(5,8,6,"a Cold Sea");
registerTileTypes(9,6,6,"an Ordered Forest");
registerTileTypes(3,4,6,"an Inn");
registerTileTypes(7,10,6,"an Inn");
registerTileTypes(1,9,6,"an Inn");
registerTileTypes(8,11,6,"an Ordered Forest");
registerTileTypes(9,5,6,"an Ivory Tower");
registerTileTypes(6,10,6,"an Ordered Forest");
registerTileTypes(6,12,6,"a Twisted Space");
registerTileTypes(3,7,6,"an Argentium Remnants");
registerTileTypes(4,8,6,"a Cold Sea");
registerTileTypes(11,11,6,"a Twisted Space");
registerTileTypes(-1,7,6,"a Twisted Space");
registerTileTypes(2,1,6,"a Twisted Space");
registerTileTypes(2,8,6,"an Ordered Forest");
registerTileTypes(12,9,6,"a Twisted Space");
registerTileTypes(10,7,6,"an Inn");
registerTileTypes(8,3,6,"a Lake of Fire");
registerTileTypes(4,1,6,"a Tavern");
registerTileTypes(0,5,6,"a Twisted Space");
registerTileTypes(13,2,6,"a Twisted Space");
registerTileTypes(1,6,6,"an Empyrean Gate");
registerTileTypes(10,11,6,"a Twisted Space");
registerTileTypes(9,8,6,"a Manufactury");
registerTileTypes(0,4,6,"a Twisted Space");
registerTileTypes(1,3,6,"a Twisted Space");
registerTileTypes(9,12,6,"a Twisted Space");
registerTileTypes(3,3,6,"a Clockwork Tower");
registerTileTypes(10,4,6,"a Crystal Castle");
registerTileTypes(8,4,6,"a Lake of Fire");
registerTileTypes(5,1,6,"an Empyrean Gate");
registerTileTypes(4,0,6,"a Twisted Void");
registerTileTypes(1,2,6,"a Twisted Space");
registerTileTypes(12,6,6,"a Twisted Space");
registerTileTypes(-1,9,6,"a Twisted Space");
registerTileTypes(13,9,6,"a Twisted Space");
registerTileTypes(1,12,6,"a Twisted Space");
registerTileTypes(12,12,6,"a Twisted Space");
registerTileTypes(7,7,6,"an Argentium Remnants");
registerTileTypes(12,7,6,"a Twisted Space");
registerTileTypes(8,7,6,"a Manufactury");
registerTileTypes(9,9,6,"a Vivarium");
registerTileTypes(6,8,6,"an Ordered Forest");
registerTileTypes(6,0,6,"a Twisted Void");
registerTileTypes(9,10,6,"a Clockwork Tower");
registerTileTypes(1,4,6,"a Twisted Space");
registerTileTypes(-1,10,6,"a Twisted Space");
registerTileTypes(9,7,6,"a Crystal Spire");
registerTileTypes(10,8,6,"an Argent Hatchery");
registerTileTypes(0,6,6,"a Twisted Space");
registerTileTypes(6,2,6,"an Ordered Forest");
registerTileTypes(0,10,6,"a Twisted Space");
registerTileTypes(5,2,6,"an Ordered Forest");
