// Amaravati Names data set
registerTileNames(21,12,6,"Twisted Space");
registerTileNames(20,8,6,"Bulwark of the Final Cause");
registerTileNames(26,11,6,"Monoculture");
registerTileNames(24,7,6,"Quenching Waters");
registerTileNames(18,6,6,"Twisted Space");
registerTileNames(27,1,6,"Constructor Secundus");
registerTileNames(18,10,6,"Twisted Space");
registerTileNames(26,6,6,"Monoculture");
registerTileNames(32,10,6,"Twisted Space");
registerTileNames(28,4,6,"Refiners Flame");
registerTileNames(31,3,6,"Twisted Space");
registerTileNames(30,6,6,"Bulwark of the Formal Cause");
registerTileNames(31,9,6,"Twisted Space");
registerTileNames(24,4,6,"Crystal Fields");
registerTileNames(19,6,6,"Twisted Space");
registerTileNames(31,5,6,"Twisted Space");
registerTileNames(27,9,6,"Manufactury");
registerTileNames(23,4,6,"Plantae");
registerTileNames(23,5,6,"Monoculture");
registerTileNames(32,8,6,"Twisted Space");
registerTileNames(31,2,6,"Twisted Space");
registerTileNames(18,7,6,"Twisted Space");
registerTileNames(32,7,6,"Twisted Space");
registerTileNames(24,0,6,"Twisted Void");
registerTileNames(21,6,6,"Monoculture");
registerTileNames(20,2,6,"Twisted Space");
registerTileNames(20,6,6,"Bulwark of the Final Cause");
registerTileNames(30,5,6,"Bulwark of the Formal Cause");
registerTileNames(32,2,6,"Twisted Space");
registerTileNames(20,4,6,"Twisted Space");
registerTileNames(28,6,6,"Monoculture");
registerTileNames(22,1,6,"Crystal Fields");
registerTileNames(26,0,6,"Twisted Void");
registerTileNames(23,11,6,"Radiant Armory");
registerTileNames(32,4,6,"Twisted Space");
registerTileNames(22,11,6,"Constructor Quintus");
registerTileNames(25,0,6,"Twisted Void");
registerTileNames(25,1,6,"Bulwark of the Material Cause");
registerTileNames(24,9,6,"Dyad");
registerTileNames(21,9,6,"Monoculture");
registerTileNames(29,3,6,"Triad");
registerTileNames(26,12,6,"Twisted Space");
registerTileNames(21,4,6,"Constructor Primus");
registerTileNames(27,10,6,"Crystal Fields");
registerTileNames(20,5,6,"Monoculture");
registerTileNames(31,6,6,"Twisted Space");
registerTileNames(31,11,6,"Twisted Space");
registerTileNames(27,2,6,"Monoculture");
registerTileNames(28,8,6,"Manufactury");
registerTileNames(18,9,6,"Twisted Space");
registerTileNames(29,11,6,"Twisted Space");
registerTileNames(30,7,6,"Bulwark of the Formal Cause");
registerTileNames(29,9,6,"Distillation");
registerTileNames(28,10,6,"Gate of Potentiality");
registerTileNames(31,12,6,"Twisted Space");
registerTileNames(28,12,6,"Twisted Space");
registerTileNames(30,1,6,"Twisted Space");
registerTileNames(26,8,6,"Manufactury");
registerTileNames(20,9,6,"Habitation");
registerTileNames(19,8,6,"Twisted Space");
registerTileNames(29,1,6,"Twisted Space");
registerTileNames(21,11,6,"Crystal Fields");
registerTileNames(25,7,6,"Monoculture");
registerTileNames(30,12,6,"Twisted Space");
registerTileNames(19,3,6,"Twisted Space");
registerTileNames(20,7,6,"Bulwark of the Final Cause");
registerTileNames(31,8,6,"Twisted Space");
registerTileNames(19,7,6,"Twisted Space");
registerTileNames(26,3,6,"Habitation");
registerTileNames(19,12,6,"Twisted Space");
registerTileNames(26,10,6,"Habitation");
registerTileNames(25,5,6,"Monoculture");
registerTileNames(32,5,6,"Twisted Space");
registerTileNames(23,9,6,"Dyad");
registerTileNames(24,8,6,"Quenching Waters");
registerTileNames(28,7,6,"Arc of the Primum Mobile");
registerTileNames(22,7,6,"Crystal Fields");
registerTileNames(24,11,6,"Habitation");
registerTileNames(31,7,6,"Twisted Space");
registerTileNames(32,1,6,"Twisted Space");
registerTileNames(23,8,6,"Quenching Waters");
registerTileNames(31,10,6,"Twisted Space");
registerTileNames(25,10,6,"Monoculture");
registerTileNames(19,9,6,"Twisted Space");
registerTileNames(19,2,6,"Twisted Space");
registerTileNames(28,1,6,"Habitation");
registerTileNames(23,0,6,"Twisted Void");
registerTileNames(20,1,6,"Twisted Space");
registerTileNames(31,1,6,"Twisted Space");
registerTileNames(23,6,6,"Tower of Law");
registerTileNames(24,3,6,"Arc of the Aether");
registerTileNames(19,4,6,"Twisted Space");
registerTileNames(21,8,6,"Monoculture");
registerTileNames(20,12,6,"Twisted Space");
registerTileNames(27,11,6,"Monoculture");
registerTileNames(25,6,6,"Monoculture");
registerTileNames(18,11,6,"Twisted Space");
registerTileNames(25,4,6,"Monoculture");
registerTileNames(24,5,6,"Monoculture");
registerTileNames(30,3,6,"Protozoa");
registerTileNames(27,8,6,"Manufactury");
registerTileNames(22,8,6,"Gate of the Locomotive");
registerTileNames(26,5,6,"Constructor Tertius");
registerTileNames(25,2,6,"Monoculture");
registerTileNames(32,9,6,"Twisted Space");
registerTileNames(28,2,6,"Monoculture");
registerTileNames(22,2,6,"Monoculture");
registerTileNames(29,6,6,"Monoculture");
registerTileNames(29,7,6,"Habitation");
registerTileNames(24,1,6,"Bulwark of the Material Cause");
registerTileNames(23,2,6,"Monoculture");
registerTileNames(30,4,6,"Triad");
registerTileNames(19,11,6,"Twisted Space");
registerTileNames(27,5,6,"Crystal Fields");
registerTileNames(29,2,6,"Monoculture");
registerTileNames(25,11,6,"Monoculture");
registerTileNames(23,3,6,"Monad");
registerTileNames(19,5,6,"Twisted Space");
registerTileNames(21,1,6,"Twisted Space");
registerTileNames(21,7,6,"Monoculture");
registerTileNames(22,0,6,"Twisted Void");
registerTileNames(19,1,6,"Twisted Space");
registerTileNames(23,7,6,"Quenching Waters");
registerTileNames(20,11,6,"Twisted Space");
registerTileNames(30,10,6,"Twisted Space");
registerTileNames(29,12,6,"Twisted Space");
registerTileNames(24,2,6,"Monoculture");
registerTileNames(24,6,6,"Crystal Fields");
registerTileNames(29,4,6,"Triad");
registerTileNames(28,9,6,"Animalia");
registerTileNames(27,7,6,"Manufactury");
registerTileNames(27,6,6,"Monoculture");
registerTileNames(22,4,6,"Habitation");
registerTileNames(31,4,6,"Twisted Space");
registerTileNames(21,5,6,"Monoculture");
registerTileNames(29,8,6,"Constructor Quartus");
registerTileNames(22,10,6,"Monoculture");
registerTileNames(28,11,6,"Monoculture");
registerTileNames(19,10,6,"Twisted Space");
registerTileNames(26,7,6,"Crystal Fields");
registerTileNames(25,12,6,"Twisted Space");
registerTileNames(22,12,6,"Bulwark of the Efficient Cause");
registerTileNames(20,10,6,"Twisted Space");
registerTileNames(23,10,6,"Monoculture");
registerTileNames(26,4,6,"Radiant Armory");
registerTileNames(30,9,6,"Habitation");
registerTileNames(23,1,6,"Fermentation");
registerTileNames(22,5,6,"Monoculture");
registerTileNames(28,5,6,"Tower of Purity");
registerTileNames(20,3,6,"Twisted Space");
registerTileNames(22,3,6,"Gate of Actuality");
registerTileNames(25,3,6,"Monoculture");
registerTileNames(23,12,6,"Bulwark of the Efficient Cause");
registerTileNames(29,5,6,"Habitation");
registerTileNames(24,10,6,"Monoculture");
registerTileNames(24,12,6,"Bulwark of the Efficient Cause");
registerTileNames(26,9,6,"Crystal Fields");
registerTileNames(22,9,6,"Arc of the Earth-Moving Fulcrum");
registerTileNames(30,8,6,"Radiant Armory");
registerTileNames(21,3,6,"Crystal Fields");
registerTileNames(26,2,6,"Monoculture");
registerTileNames(27,3,6,"Refiners Flame");
registerTileNames(21,2,6,"Monoculture");
registerTileNames(32,3,6,"Twisted Space");
registerTileNames(32,6,6,"Twisted Space");
registerTileNames(26,1,6,"Bulwark of the Material Cause");
registerTileNames(29,10,6,"Crystal Fields");
registerTileNames(28,3,6,"Refiners Flame");
registerTileNames(30,11,6,"Twisted Space");
registerTileNames(25,8,6,"Monoculture");
registerTileNames(21,10,6,"Monoculture");
registerTileNames(22,6,6,"Crystal Fields");
registerTileNames(30,2,6,"Twisted Space");
registerTileNames(25,9,6,"Monoculture");
registerTileNames(18,8,6,"Twisted Space");
registerTileNames(27,12,6,"Twisted Space");
registerTileNames(27,4,6,"Refiners Flame");

// Amaravati Types data set
registerTileTypes(28,8,6,"a Manufactury");
registerTileTypes(29,9,6,"a Tavern");
registerTileTypes(26,8,6,"a Manufactury");
registerTileTypes(26,9,6,"an Argentium Remnants");
registerTileTypes(21,10,6,"an Ordered Forest");
registerTileTypes(26,2,6,"an Ordered Forest");
registerTileTypes(20,1,6,"a Twisted Space");
registerTileTypes(20,6,6,"an Empyrean Gate");
registerTileTypes(20,2,6,"a Twisted Space");
registerTileTypes(26,12,6,"a Twisted Space");
registerTileTypes(29,1,6,"a Twisted Space");
registerTileTypes(29,6,6,"an Ordered Forest");
registerTileTypes(32,6,6,"a Twisted Space");
registerTileTypes(20,9,6,"an Inn");
registerTileTypes(21,2,6,"an Ordered Forest");
registerTileTypes(23,12,6,"an Empyrean Gate");
registerTileTypes(21,12,6,"a Twisted Space");
registerTileTypes(22,8,6,"a Clockwork Tower");
registerTileTypes(19,10,6,"a Twisted Space");
registerTileTypes(26,7,6,"an Argentium Remnants");
registerTileTypes(29,11,6,"a Twisted Space");
registerTileTypes(19,12,6,"a Twisted Space");
registerTileTypes(28,10,6,"a Clockwork Tower");
registerTileTypes(19,4,6,"a Twisted Space");
registerTileTypes(21,6,6,"an Ordered Forest");
registerTileTypes(24,6,6,"an Argentium Remnants");
registerTileTypes(24,0,6,"a Twisted Void");
registerTileTypes(25,7,6,"an Ordered Forest");
registerTileTypes(24,8,6,"a Cold Sea");
registerTileTypes(23,10,6,"an Ordered Forest");
registerTileTypes(20,11,6,"a Twisted Space");
registerTileTypes(30,7,6,"an Empyrean Gate");
registerTileTypes(21,8,6,"an Ordered Forest");
registerTileTypes(25,10,6,"an Ordered Forest");
registerTileTypes(19,7,6,"a Twisted Space");
registerTileTypes(22,0,6,"a Twisted Void");
registerTileTypes(25,6,6,"an Ordered Forest");
registerTileTypes(31,11,6,"a Twisted Space");
registerTileTypes(20,7,6,"an Empyrean Gate");
registerTileTypes(18,8,6,"a Twisted Space");
registerTileTypes(32,8,6,"a Twisted Space");
registerTileTypes(30,8,6,"a Radiant Armory");
registerTileTypes(28,3,6,"a Lake of Fire");
registerTileTypes(20,12,6,"a Twisted Space");
registerTileTypes(30,4,6,"a Crystal Castle");
registerTileTypes(23,1,6,"a Tavern");
registerTileTypes(24,11,6,"an Inn");
registerTileTypes(24,5,6,"an Ordered Forest");
registerTileTypes(18,7,6,"a Twisted Space");
registerTileTypes(23,6,6,"an Ivory Tower");
registerTileTypes(27,10,6,"an Argentium Remnants");
registerTileTypes(25,4,6,"an Ordered Forest");
registerTileTypes(23,0,6,"a Twisted Void");
registerTileTypes(22,11,6,"an Argent Hatchery");
registerTileTypes(26,5,6,"an Argent Hatchery");
registerTileTypes(28,9,6,"a Vivarium");
registerTileTypes(31,9,6,"a Twisted Space");
registerTileTypes(22,9,6,"a Crystal Spire");
registerTileTypes(19,11,6,"a Twisted Space");
registerTileTypes(25,3,6,"an Ordered Forest");
registerTileTypes(25,9,6,"an Ordered Forest");
registerTileTypes(30,6,6,"an Empyrean Gate");
registerTileTypes(26,4,6,"a Radiant Armory");
registerTileTypes(22,2,6,"an Ordered Forest");
registerTileTypes(20,5,6,"an Ordered Forest");
registerTileTypes(25,5,6,"an Ordered Forest");
registerTileTypes(27,11,6,"an Ordered Forest");
registerTileTypes(21,9,6,"an Ordered Forest");
registerTileTypes(32,2,6,"a Twisted Space");
registerTileTypes(21,4,6,"an Argent Hatchery");
registerTileTypes(29,4,6,"a Crystal Castle");
registerTileTypes(18,11,6,"a Twisted Space");
registerTileTypes(18,6,6,"a Twisted Space");
registerTileTypes(25,8,6,"an Ordered Forest");
registerTileTypes(27,2,6,"an Ordered Forest");
registerTileTypes(25,2,6,"an Ordered Forest");
registerTileTypes(29,3,6,"a Crystal Castle");
registerTileTypes(19,5,6,"a Twisted Space");
registerTileTypes(27,9,6,"a Manufactury");
registerTileTypes(24,7,6,"a Cold Sea");
registerTileTypes(24,3,6,"a Greater Spire");
registerTileTypes(27,8,6,"a Manufactury");
registerTileTypes(21,1,6,"a Twisted Space");
registerTileTypes(32,1,6,"a Twisted Space");
registerTileTypes(26,3,6,"an Inn");
registerTileTypes(28,5,6,"an Ivory Tower");
registerTileTypes(30,12,6,"a Twisted Space");
registerTileTypes(22,6,6,"an Argentium Remnants");
registerTileTypes(23,2,6,"an Ordered Forest");
registerTileTypes(18,10,6,"a Twisted Space");
registerTileTypes(27,6,6,"an Ordered Forest");
registerTileTypes(32,10,6,"a Twisted Space");
registerTileTypes(25,0,6,"a Twisted Void");
registerTileTypes(32,7,6,"a Twisted Space");
registerTileTypes(21,7,6,"an Ordered Forest");
registerTileTypes(25,12,6,"a Twisted Space");
registerTileTypes(27,12,6,"a Twisted Space");
registerTileTypes(28,2,6,"an Ordered Forest");
registerTileTypes(31,8,6,"a Twisted Space");
registerTileTypes(23,8,6,"a Cold Sea");
registerTileTypes(28,12,6,"a Twisted Space");
registerTileTypes(19,6,6,"a Twisted Space");
registerTileTypes(26,6,6,"an Ordered Forest");
registerTileTypes(22,7,6,"an Argentium Remnants");
registerTileTypes(18,9,6,"a Twisted Space");
registerTileTypes(29,12,6,"a Twisted Space");
registerTileTypes(31,7,6,"a Twisted Space");
registerTileTypes(32,5,6,"a Twisted Space");
registerTileTypes(30,9,6,"an Inn");
registerTileTypes(19,8,6,"a Twisted Space");
registerTileTypes(31,6,6,"a Twisted Space");
registerTileTypes(32,4,6,"a Twisted Space");
registerTileTypes(25,11,6,"an Ordered Forest");
registerTileTypes(19,2,6,"a Twisted Space");
registerTileTypes(28,7,6,"a Crystal Spire");
registerTileTypes(32,3,6,"a Twisted Space");
registerTileTypes(26,10,6,"an Inn");
registerTileTypes(30,11,6,"a Twisted Space");
registerTileTypes(31,2,6,"a Twisted Space");
registerTileTypes(27,5,6,"an Argentium Remnants");
registerTileTypes(29,7,6,"an Inn");
registerTileTypes(23,4,6,"a Vivarium");
registerTileTypes(23,3,6,"a Crystal Castle");
registerTileTypes(32,9,6,"a Twisted Space");
registerTileTypes(24,4,6,"an Argentium Remnants");
registerTileTypes(20,3,6,"a Twisted Space");
registerTileTypes(29,5,6,"an Inn");
registerTileTypes(31,5,6,"a Twisted Space");
registerTileTypes(29,10,6,"an Argentium Remnants");
registerTileTypes(21,11,6,"an Argentium Remnants");
registerTileTypes(21,3,6,"an Argentium Remnants");
registerTileTypes(26,1,6,"an Empyrean Gate");
registerTileTypes(27,3,6,"a Lake of Fire");
registerTileTypes(24,1,6,"an Empyrean Gate");
registerTileTypes(23,7,6,"a Cold Sea");
registerTileTypes(28,4,6,"a Lake of Fire");
registerTileTypes(30,1,6,"a Twisted Space");
registerTileTypes(24,2,6,"an Ordered Forest");
registerTileTypes(23,9,6,"a Crystal Castle");
registerTileTypes(27,7,6,"a Manufactury");
registerTileTypes(23,5,6,"an Ordered Forest");
registerTileTypes(27,1,6,"an Argent Hatchery");
registerTileTypes(30,2,6,"a Twisted Space");
registerTileTypes(31,4,6,"a Twisted Space");
registerTileTypes(30,10,6,"a Twisted Space");
registerTileTypes(30,3,6,"a Vivarium");
registerTileTypes(22,10,6,"an Ordered Forest");
registerTileTypes(22,3,6,"a Clockwork Tower");
registerTileTypes(19,1,6,"a Twisted Space");
registerTileTypes(19,9,6,"a Twisted Space");
registerTileTypes(31,3,6,"a Twisted Space");
registerTileTypes(23,11,6,"a Radiant Armory");
registerTileTypes(26,11,6,"an Ordered Forest");
registerTileTypes(26,0,6,"a Twisted Void");
registerTileTypes(24,9,6,"a Crystal Castle");
registerTileTypes(28,6,6,"an Ordered Forest");
registerTileTypes(29,8,6,"an Argent Hatchery");
registerTileTypes(31,10,6,"a Twisted Space");
registerTileTypes(24,10,6,"an Ordered Forest");
registerTileTypes(27,4,6,"a Lake of Fire");
registerTileTypes(19,3,6,"a Twisted Space");
registerTileTypes(28,1,6,"an Inn");
registerTileTypes(31,1,6,"a Twisted Space");
registerTileTypes(29,2,6,"an Ordered Forest");
registerTileTypes(22,5,6,"an Ordered Forest");
registerTileTypes(22,1,6,"an Argentium Remnants");
registerTileTypes(25,1,6,"an Empyrean Gate");
registerTileTypes(20,8,6,"an Empyrean Gate");
registerTileTypes(31,12,6,"a Twisted Space");
registerTileTypes(22,12,6,"an Empyrean Gate");
registerTileTypes(20,4,6,"a Twisted Space");
registerTileTypes(24,12,6,"an Empyrean Gate");
registerTileTypes(30,5,6,"an Empyrean Gate");
registerTileTypes(20,10,6,"a Twisted Space");
registerTileTypes(28,11,6,"an Ordered Forest");
registerTileTypes(22,4,6,"an Inn");
registerTileTypes(21,5,6,"an Ordered Forest");
